# Generated by Django 5.2.1 on 2025-05-29 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notices', '0001_initial'),
        ('properties', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='properties.property'),
        ),
        migrations.AddField(
            model_name='noticeview',
            name='notice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='notices.notice'),
        ),
        migrations.AddField(
            model_name='noticeview',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_notices', to='tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='noticeview',
            unique_together={('notice', 'tenant')},
        ),
    ]
