# Generated by Django 5.2.1 on 2025-06-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='send_sms',
            field=models.BooleanField(default=False),
        ),
    ]
