# Generated by Django 5.2.1 on 2025-06-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_notice_send_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice_type',
            field=models.CharField(choices=[('general', 'General Announcement'), ('rent', 'Rent & Payments'), ('maintenance', 'Maintenance & Repairs'), ('inspection', 'Inspection & Access'), ('eviction', 'Eviction & Legal'), ('amenities', 'Amenities & Facilities'), ('policy', 'Policy & Rules Update'), ('event', 'Community Event'), ('emergency', 'Emergency Alert'), ('utility', 'Utility & Service')], default='general', max_length=20),
        ),
    ]
