# Generated by Django 5.2.1 on 2025-06-07 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_fix_mpesa_payment_property_nulls'),
        ('properties', '0005_merge_0002_propertympesamconfig_0004_unit_unit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesapayment',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_payments', to='properties.property'),
        ),
    ]
