# Generated by Django 5.2.1 on 2025-06-07 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_fix_mpesa_payment_property_nulls'),
    ]

    operations = [
    ]
