# Generated by Django 5.2.1 on 2025-06-07 17:46

from django.db import migrations


def fix_mpesa_payment_property_nulls(apps, schema_editor):
    """
    Fix MpesaPayment records with null property_id by setting it from rent_payment.unit.property
    """
    MpesaPayment = apps.get_model('payments', 'MpesaPayment')
    Property = apps.get_model('properties', 'Property')
    
    # Find all MpesaPayment records with null property_id
    null_property_payments = MpesaPayment.objects.filter(property__isnull=True)
    
    # Get the first property as a fallback (if needed)
    default_property = Property.objects.first()
    
    updated_count = 0
    for payment in null_property_payments:
        if payment.rent_payment and payment.rent_payment.unit and payment.rent_payment.unit.property:
                        # Set property from rent_payment.unit.property
            payment.property = payment.rent_payment.unit.property
            
            # Also set organization from property if it's null
            if not payment.organization_id and payment.property and hasattr(payment.property, 'organization'):
                payment.organization = payment.property.organization
                
            payment.save()
            updated_count += 1
        elif default_property:
            # Fallback to the first property if available
            payment.property = default_property
            payment.save()
            updated_count += 1
    
    print(f"Fixed {updated_count} MpesaPayment records with null property_id")


def reverse_fix_mpesa_payment_property_nulls(apps, schema_editor):
    """
    Reverse operation - not needed since we're fixing data integrity
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_mpesapayment_property_alter_mpesapayment_organization'),
        ('properties', '0005_merge_0002_propertympesamconfig_0004_unit_unit_type'),
    ]

    operations = [
        migrations.RunPython(
            fix_mpesa_payment_property_nulls,
            reverse_fix_mpesa_payment_property_nulls
        ),
    ]
