# Generated by Django 5.2.1 on 2025-06-12 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organizationrole_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('role_type', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('manager', 'Manager'), ('member', 'Member'), ('guest', 'Guest')], max_length=20)),
                ('is_system_role', models.BooleanField(default=True)),
                ('default_can_manage_users', models.BooleanField(default=False)),
                ('default_can_manage_billing', models.BooleanField(default=False)),
                ('default_can_manage_properties', models.BooleanField(default=False)),
                ('default_can_manage_tenants', models.BooleanField(default=False)),
                ('default_can_view_reports', models.BooleanField(default=False)),
                ('default_can_manage_roles', models.BooleanField(default=False)),
                ('default_can_manage_system_settings', models.BooleanField(default=False)),
                ('default_can_view_dashboard', models.BooleanField(default=False)),
                ('default_can_manage_tickets', models.BooleanField(default=False)),
                ('default_manage_notices', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Base Role',
                'verbose_name_plural': 'Base Roles',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='organizationrole',
            options={'ordering': ['organization', 'base_role__name'], 'verbose_name': 'Organization Role', 'verbose_name_plural': 'Organization Roles'},
        ),
        migrations.AddField(
            model_name='organizationrole',
            name='_legacy_can_manage_billing',
            field=models.BooleanField(default=False, help_text='Legacy field - use computed property'),
        ),
        migrations.AddField(
            model_name='organizationrole',
            name='_legacy_can_manage_properties',
            field=models.BooleanField(default=False, help_text='Legacy field - use computed property'),
        ),
        migrations.AddField(
            model_name='organizationrole',
            name='_legacy_can_manage_tenants',
            field=models.BooleanField(default=False, help_text='Legacy field - use computed property'),
        ),
        migrations.AddField(
            model_name='organizationrole',
            name='_legacy_can_manage_users',
            field=models.BooleanField(default=False, help_text='Legacy field - use computed property'),
        ),
        migrations.AddField(
            model_name='organizationrole',
            name='_legacy_can_view_reports',
            field=models.BooleanField(default=False, help_text='Legacy field - use computed property'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationrole',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='organizationrole',
            name='base_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_roles', to='organizations.baserole'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationrole',
            unique_together={('organization', 'base_role')},
        ),
        migrations.RemoveField(
            model_name='organizationrole',
            name='can_manage_billing',
        ),
        migrations.RemoveField(
            model_name='organizationrole',
            name='can_manage_properties',
        ),
        migrations.RemoveField(
            model_name='organizationrole',
            name='can_manage_tenants',
        ),
        migrations.RemoveField(
            model_name='organizationrole',
            name='can_manage_users',
        ),
        migrations.RemoveField(
            model_name='organizationrole',
            name='can_view_reports',
        ),
        migrations.RemoveField(
            model_name='organizationrole',
            name='description',
        ),
        migrations.RemoveField(
            model_name='organizationrole',
            name='name',
        ),
        migrations.RemoveField(
            model_name='organizationrole',
            name='role_type',
        ),
        migrations.RemoveField(
            model_name='organizationrole',
            name='slug',
        ),
        migrations.CreateModel(
            name='OrganizationRoleCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_manage_users', models.BooleanField(blank=True, null=True)),
                ('can_manage_billing', models.BooleanField(blank=True, null=True)),
                ('can_manage_properties', models.BooleanField(blank=True, null=True)),
                ('can_manage_tenants', models.BooleanField(blank=True, null=True)),
                ('can_view_reports', models.BooleanField(blank=True, null=True)),
                ('can_manage_roles', models.BooleanField(blank=True, null=True)),
                ('can_manage_system_settings', models.BooleanField(blank=True, null=True)),
                ('can_view_dashboard', models.BooleanField(blank=True, null=True)),
                ('can_manage_tickets', models.BooleanField(blank=True, null=True)),
                ('manage_notices', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customizations', to='organizations.baserole')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_customizations', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Organization Role Customization',
                'verbose_name_plural': 'Organization Role Customizations',
                'ordering': ['organization', 'base_role'],
                'unique_together': {('organization', 'base_role')},
            },
        ),
    ]
