# Generated by Django 5.2.1 on 2025-06-12 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_fix_null_base_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationrole',
            name='base_role',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='organization_roles', to='organizations.baserole'),
            preserve_default=False,
        ),
    ]
