# Generated by Django 5.2.1 on 2025-05-29 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0002_initial'),
        ('organizations', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentanalytics',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='propertymetric',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='properties.property'),
        ),
        migrations.AddField(
            model_name='report',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='smsanalytics',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentanalytics',
            unique_together={('organization', 'period')},
        ),
        migrations.AlterUniqueTogether(
            name='propertymetric',
            unique_together={('property', 'period_start', 'period_end')},
        ),
        migrations.AlterUniqueTogether(
            name='smsanalytics',
            unique_together={('organization', 'period')},
        ),
    ]
