# Generated by Django 5.2.1 on 2025-06-02 10:25

import properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=properties.models.property_image_path),
        ),
    ]
