# Generated by Django 5.2.1 on 2025-06-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(blank=True, help_text='Type of unit (e.g., Studio, 1BR, 2BR)', max_length=50, null=True),
        ),
    ]
