# Generated by Django 5.2.1 on 2025-06-04 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_propertympesamconfig'),
        ('properties', '0004_unit_unit_type'),
    ]

    operations = [
    ]
