# Generated by Django 5.2.1 on 2025-06-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_merge_0002_propertympesamconfig_0004_unit_unit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=20000, help_text='Default security deposit amount for this unit', max_digits=10),
        ),
    ]
