# Generated by Django 5.2.1 on 2025-06-12 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_initial'),
        ('organizations', '0006_make_base_role_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_providers', to='organizations.organization'),
        ),
    ]
